[tool.ruff]
line-length = 144

# Choose a comprehensive set. This is a good starting point:
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings (includes W292)
    "F",  # Pyflakes (undefined names, unused imports/variables)
    "I",  # isort (import sorting)
    "UP", # pyupgrade (modernize Python syntax)
    # "N",  # pep8-naming (naming conventions)
    # "B",  # flake8-bugbear (potential bugs/design problems)
    # "SIM",# flake8-simplify (simpler code patterns)
    # "C90",# McCabe complexity
    # "RUF", # Consider adding some or all Ruff-specific rules
]

# Example of configuring a specific rule from a category
[tool.ruff.mccabe]
max-complexity = 10 # Default is 10, adjust as needed

# If you want to ignore specific rules from the selected categories:
# ignore = ["N803"] # Example: ignore a specific pep8-naming rule if it's problematic for your project

# You can discover all rules by running:
# ruff rule --all
# Or browse them on the Ruff documentation website.

[tool.ruff.per-file-ignores]
"**/__init__.py" = ["F401"] # Ignores F401 for all __init__.py files